name: 🔎📦 Check for unused dependencies

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run depcheck
      continue-on-error: true
      id: depcheck
      run: npx depcheck -y --json > unused-deps.json

    - name: Parse unused dependencies
      id: parse-deps
      continue-on-error: true
      run: |
        unused=$(jq -r '.dependencies[]' < unused-deps.json)
        echo "::set-output name=unused_deps::$unused"

    - name: Create branches and PRs for unused dependencies
      if: steps.parse-deps.outputs.unused_deps != ''
      run: |
        # Config git client
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

        for dep in $(echo ${{ steps.parse-deps.outputs.unused_deps }}); do
          branch_name="remove-$dep"
          pr_exists=$(gh pr list --label unused --search "$branch_name" --json number -q '.[].number')

          echo "$pr_exists"

          # Check if the PR already exists
          if [ -z "$pr_exists" ]; then
            git checkout -b "$branch_name"
            npm uninstall $dep
            git add package.json package-lock.json
            git commit -m "Remove unused dependency: $dep"
            git push origin "$branch_name"
            gh pr create --title "Remove unused dependency: $dep" --body "This PR removes the unused dependency: $dep" --label dependencies --label unused
          else
            echo "PR already exists for $dep, skipping."
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
