name: ✅📦 Depcheck Unused Dependencies

on:
  push:
    branches: [feat/ai-tour, main]
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow   


permissions:
  contents: read # Allows the workflow to read the repository contents
  pull-requests: write # Allows the workflow to create pull requests

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Run depcheck
        run: |
          #npx depcheck -y > depcheck-output.txt
          npx depcheck -y
