name: Depcheck

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Ejecuta semanalmente

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run depcheck
      continue-on-error: true
      id: depcheck
      run: npx depcheck --json > unused-deps.json

    - name: Parse unused dependencies
      id: parse-deps
      continue-on-error: true
      run: |
        unused=$(jq -r '.dependencies[]' < unused-deps.json)
        echo "::set-output name=unused_deps::$unused"

    - name: Create branches and PRs for unused dependencies
      if: steps.parse-deps.outputs.unused_deps != ''
      run: |
        for dep in $(echo ${{ steps.parse-deps.outputs.unused_deps }}); do
          git checkout -b "remove-$dep"
          npm uninstall $dep
          git add package.json package-lock.json
          git commit -m "Remove unused dependency: $dep"
          git push origin "remove-$dep"
          gh pr create --title "Remove unused dependency: $dep" --body "This PR removes the unused dependency: $dep"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
